version: '3.4'

services:
  backendnode:
    image: backendnode
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3334:3334
